In [2]:
import numpy as np

In [5]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [7]:
a=np.array([[6, 7, 8] ,[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [11]:
a[1,2]

3

In [13]:
a[2,1]

3

In [16]:
a[2,0]

9

In [19]:
#0 to 2 but 2 will not be included here and of 2nd column.
b=a[0:2,2]
b

array([8, 3])

In [21]:
a[-1]

array([9, 3, 2])

In [23]:
a[-1,0:2]

array([9, 3])

In [25]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [27]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [29]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [31]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [37]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [39]:
x=np.arange(30).reshape(2,15)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [46]:
result = np.hsplit(x,3)
result[0],result[1],result[2]

(array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]]))

In [47]:
a=np.arange(12).reshape(3,4)

In [49]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [55]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [66]:
y=np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.savetxt("text.txt",y)

In [72]:
y=np.loadtxt("text.txt")
y

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [75]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
for x in np.nditer(x,order='f'):
    print(x)

11


In [82]:
for x in np.nditer(x,order='f',flags=['external_loop']):
    print(x)

[11]


In [87]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x
a

array([[    0,     1,   256,  6561],
       [65536,     1,     1,     1],
       [    1,     1,     1,     1]])

In [95]:
u = np.arange(12).reshape(3,4)

In [96]:
u

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
v = np.arange(3,15,5).reshape(3,1)
v

array([[ 3],
       [ 8],
       [13]])

In [99]:
for f,g in np.nditer([u,v]):
    print(f,g)

1 True
