In [2]:
import numpy as np

In [5]:
m1 = np.array([[ 5, 12,  6],[-3,  0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [7]:
m2 = np.array([[ 9, 8, 7],[1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [9]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [12]:
t.shape

(2, 2, 3)

In [15]:
m1 +m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [17]:
m2 - m1 

array([[  4,  -4,   1],
       [  4,   3, -19]])

In [19]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [21]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([1,2,3,4,5])
v1,v2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [24]:
v1-v2

array([0, 0, 0, 0, 0])

# v1+v2

In [27]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])