In [2]:
import numpy as np

In [56]:
a = np.array([[5,12,6],[-3,0,14]])
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [20]:
a.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [10]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])
np.dot(x,y)

-66

In [12]:
np.dot(10,-2)

-20

In [14]:
x

array([ 2,  8, -4])

In [6]:
import numpy as np
x = np.array([2,8,-4])

In [8]:
5*x

array([ 10,  40, -20])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
a = np.array([[5,12,6],[-3,0,14]])
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [26]:
a.shape

(2, 3)

In [29]:
a.reshape(3,2)

array([[ 5, 12],
       [ 6, -3],
       [ 0, 14]])

In [31]:
a.reshape(6,1)

array([[ 5],
       [12],
       [ 6],
       [-3],
       [ 0],
       [14]])

In [34]:
a.ravel()

array([ 5, 12,  6, -3,  0, 14])

In [36]:
b=a.ravel()

In [39]:
b

array([ 5, 12,  6, -3,  0, 14])

In [42]:
a.min()

-3

In [43]:
a.max()

14

In [44]:
a.sum()

34

In [45]:
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [48]:
c=a.reshape((3,2))
c

array([[ 5, 12],
       [ 6, -3],
       [ 0, 14]])

In [49]:
c.sum(axis=0)

array([11, 23])

In [51]:
np.sqrt(a)

C:\Users\shrey\AppData\Local\Temp\ipykernel_17052\2835837605.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([[2.23606798, 3.46410162, 2.44948974],
       [       nan, 0.        , 3.74165739]])

In [54]:
d=np.array([ 5, 12,  6])
d

array([ 5, 12,  6])

In [57]:
np.sqrt(d)

array([2.23606798, 3.46410162, 2.44948974])

In [62]:
x=np.array([5,12,6])
y=np.array([-3,0,14])
x,y

(array([ 5, 12,  6]), array([-3,  0, 14]))

In [63]:
x.dot(y)

69